// packages/richtext/playground/react/src/RichText.tsx
import type { SbBlokData } from '@storyblok/react';
import { StoryblokComponent, useStoryblok } from '@storyblok/react';
import StoryblokRichText from './components/StoryblokRichText';

export default function RichText() {
  const story = useStoryblok('richtext', { version: 'draft' });

  if (!story?.content) {
    return <div>Loading...</div>;
  }

  const richtext = story.content?.richText;

  return (
    <div>
      <h1>Richtext </h1>
      <StoryblokRichText
        doc={richtext}
        components={{
          blok: ({ body }) =>
            body?.map((blok: SbBlokData) => <StoryblokComponent blok={blok} key={blok._uid} />),
          link: CustomBlokComponent,
        }}
      />
    </div>
  );
}
function CustomBlokComponent(props: any) {
  const { children, ...attributes } = props;
  return <a {...attributes}>{children}</a>;
}

// packages/nuxt/playground/pages/richtext.vue
<script setup lang="ts">
import { NuxtLink } from '#build/components';
import { MarkTypes, type StoryblokRichTextNode } from '@storyblok/vue';

const story = await useAsyncStoryblok('vue/test-richtext', {
  api: {
    version: 'draft',
  },
});

const resolvers = {
  [MarkTypes.LINK]: (node: StoryblokRichTextNode<VNode>) => {
    return node.attrs?.linktype === 'STORY'
      ? h(
          NuxtLink,
          {
            to: node.attrs?.href,
            target: node.attrs?.target,
          },
          node.text,
        )
      : h(
          'a',
          {
            href: node.attrs?.href,
            target: node.attrs?.target,
          },
          node.text,
        );
  },
};
</script>

<template>
  <StoryblokRichText
    v-if="story.content.richText"
    :doc="story.content.richText"
    :resolvers="resolvers"
  />
</template>
