// packages/react/playground/react/App.tsx
import React from "react";
import { BrowserRouter, Link, Route, Routes } from "react-router";
import Home from "./pages/Home";
import RichtextPage from "./pages/RichtextPage";

function App() {
  return (
    <BrowserRouter>
      <div>
        <nav className=" py-8 container mx-auto mb-8">
          <ul className="flex gap-4">
            <li>
              <Link to="/react">Home</Link>
            </li>
            <li>
              <Link to="/react/test-richtext">Richtext</Link>
            </li>
          </ul>
        </nav>
        <div className="prose mx-auto">
          <Routes>
            <Route path="/" element={<Home />} />
            <Route path="react" element={<Home />} />
            <Route path="react/test-richtext" element={<RichtextPage />} />
          </Routes>
        </div>
      </div>
    </BrowserRouter>
  );
}

export default App;

// packages/vue/playground/vue/src/App.vue
<script setup lang="ts">
import { watch } from 'vue';
import { useRoute } from 'vue-router';

const route = useRoute();
function setBodyClass(routeName: string) {
  document.title = `Core Playground - ${routeName}`;
  document.body.className = routeName;
}
watch([route], () => setBodyClass(route.name?.toString() ?? ''));
</script>

<template>
  <Suspense>
    <template #default>
      <div class="prose mx-auto">
        <nav>
          <ul class="flex gap-4 list-none">
            <li>
              <RouterLink to="/">Home</RouterLink>
            </li>
            <li>
              <RouterLink to="/vue/test-richtext">Richtext</RouterLink>
            </li>
          </ul>
        </nav>
        <RouterView />
      </div>
     
    </template>

    <template #fallback>
      <div>Loading...</div>
    </template>
  </Suspense>
</template>
