// packages/react/playground/react/components/feature.tsx
import React from "react";
import type { SbBlokData } from "@storyblok/react";
import { storyblokEditable } from "@storyblok/react";

interface FeatureProps {
  blok: SbBlokData;
}

const Feature = ({ blok }: FeatureProps) => {
  return (
    <div {...storyblokEditable(blok)} key={blok._uid} data-test="feature">
      <div>
        <div>{blok.name as string}</div>
        <p>{blok.description as string}</p>
      </div>
    </div>
  );
};

export default Feature;

// packages/vue/playground/vue/src/components/Feature.vue
<script setup lang="ts">
import type { SbBlokData } from "@storyblok/vue";

defineProps<{ blok: SbBlokData & { name?: string } }>();

function featureMethod() {
  // eslint-disable-next-line no-console
  console.log("Hi from Feature.vue");
}

defineExpose({
  featureMethod,
});
</script>

<template>
  <div v-editable="blok" class="py-2" data-test="feature">
    <h1 class="text-lg">{{ blok.name }}</h1>
  </div>
</template>
