// packages/react/playground/react/components/grid.tsx
import React from "react";
import type { SbBlokData } from "@storyblok/react";
import { StoryblokComponent, storyblokEditable } from "@storyblok/react";

interface GridProps {
  blok: SbBlokData;
}

const Grid = ({ blok }: GridProps) => (
  <ul {...storyblokEditable(blok)} key={blok._uid} data-test="grid">
    {(blok.columns as SbBlokData[]).map((nestedBlok) => (
      <li key={nestedBlok._uid}>
        <StoryblokComponent blok={nestedBlok} />
      </li>
    ))}
  </ul>
);

export default Grid;

// packages/vue/playground/vue/src/components/Grid.vue
<script setup lang="ts">
import type { SbBlokData } from '@storyblok/vue';

defineProps<{ blok: SbBlokData & { columns?: SbBlokData[] } }>();
</script>

<template>
  <div v-editable="blok" class="flex py-8 mb-6" data-test="grid">
    <div v-for="inblok in blok.columns" :key="inblok._uid" class="flex-auto px-6">
      <StoryblokComponent :blok="inblok" />
    </div>
  </div>
</template>
