// packages/react/playground/integration-tests/components/page.tsx
import type { StoryblokComponentProps } from "@storyblok/react";
import { StoryblokComponent } from "../storyblok";
import { Block } from "../schema/blocks";

type PageProps = StoryblokComponentProps<Block<"page">>;

const Page = ({ block, editable }: PageProps) => (
  <div {...editable} data-test="page">
    {block.body?.map((nestedBlock) => (
      <div key={nestedBlock._uid}>
        <StoryblokComponent block={nestedBlock} />
      </div>
    ))}
  </div>
);

export default Page;

// packages/vue/playground/vue/src/components/Page.vue
<script setup lang="ts">
import type { SbBlokData } from "@storyblok/vue";

defineProps<{ blok: SbBlokData & { body?: SbBlokData[] } }>();
</script>

<template>
  <div v-editable="blok" class="px-6" data-test="page">
    <StoryblokComponent v-for="inblok in blok.body" :key="inblok._uid" :blok="inblok" />
    <slot name="footer"></slot>
  </div>
</template>
