// packages/vue/playground/vue/src/components/Page.vue
<script setup lang="ts">
import type { SbBlokData } from "@storyblok/vue";

defineProps<{ blok: SbBlokData & { body?: SbBlokData[] } }>();
</script>

<template>
  <div v-editable="blok" class="px-6" data-test="page">
    <StoryblokComponent v-for="inblok in blok.body" :key="inblok._uid" :blok="inblok" />
    <slot name="footer"></slot>
  </div>
</template>

// packages/react/playground/react/components/page.tsx
import React from "react";
import type { SbBlokData } from "@storyblok/react";
import { StoryblokComponent, storyblokEditable } from "@storyblok/react";

interface PageProps {
  blok: SbBlokData;
}

const Page = ({ blok }: PageProps) => (
  <div {...storyblokEditable(blok)} key={blok._uid} data-test="page">
    {blok.body
      ? (blok.body as SbBlokData[]).map((nestedBlok) => (
          <div key={nestedBlok._uid}>
            <StoryblokComponent blok={nestedBlok} />
          </div>
        ))
      : null}
  </div>
);

export default Page;
