// packages/vue/playground/vue/src/components/Teaser.vue
<script setup lang="ts">
import type { SbBlokData } from '@storyblok/vue';

defineProps<{ blok: SbBlokData & { headline?: string } }>();
</script>

<template>
  <div
    v-editable="blok"
    :cat="$attrs.cat"
    class="py-8 mb-6 text-5xl font-bold text-center"
    data-test="teaser"
  >
    {{ blok.headline }}
  </div>
</template>

// packages/react/playground/react/components/teaser.tsx
import type { StoryblokBlockComponentProps } from "@storyblok/react";

type TeaserProps = StoryblokBlockComponentProps<{ headline: string }>;

const Teaser = ({ block, editable }: TeaserProps) => (
  <div {...editable} data-test="teaser">
    <h2>{block.headline}</h2>
  </div>
);

export default Teaser;
