// packages/vue/playground/vue/src/components/Page.vue
<script setup lang="ts">
import type { SbBlokData } from "@storyblok/vue";

defineProps<{ blok: SbBlokData & { body?: SbBlokData[] } }>();
</script>

<template>
  <div v-editable="blok" class="px-6" data-test="page">
    <StoryblokComponent v-for="inblok in blok.body" :key="inblok._uid" :blok="inblok" />
    <slot name="footer"></slot>
  </div>
</template>

// packages/react/playground/next-13-pages-router/components/page.tsx
import React from "react";
import type { SbBlokData } from "@storyblok/react";
import { StoryblokComponent, storyblokEditable } from "@storyblok/react";

interface PageProps {
  blok: SbBlokData;
}

const Page = ({ blok }: PageProps) => (
  <div {...storyblokEditable(blok)} key={blok._uid} data-test="page">
    {(blok.body as SbBlokData[] | undefined)?.map((nestedBlok) => (
      <StoryblokComponent key={nestedBlok._uid} blok={nestedBlok} />
    ))}
  </div>
);

export default Page;
