// packages/vue/playground/vue/src/components/Teaser.vue
<script setup lang="ts">
import type { SbBlokData } from '@storyblok/vue';

defineProps<{ blok: SbBlokData & { headline?: string } }>();
</script>

<template>
  <div
    v-editable="blok"
    :cat="$attrs.cat"
    class="py-8 mb-6 text-5xl font-bold text-center"
    data-test="teaser"
  >
    {{ blok.headline }}
  </div>
</template>

// packages/react/playground/next-13-pages-router/components/teaser.tsx
import React from "react";
import type { SbBlokData } from "@storyblok/react";
import { storyblokEditable } from "@storyblok/react";

interface TeaserProps {
  blok: SbBlokData;
}

const Teaser = ({ blok }: TeaserProps) => {
  return (
    <div {...storyblokEditable(blok)} key={blok._uid} data-test="teaser">
      <div>
        <h2>{blok.headline as string}</h2>
      </div>
    </div>
  );
};

export default Teaser;
