// packages/react/playground/next-latest/src/app/components/Header.tsx
import Link from "next/link";

export default function Header() {
  return (
    <header className="mb-8">
      <h1 className="mb-8 text-4xl font-bold dark:text-white">Storyblok Next.js 16 Example</h1>
      <nav className="flex items-center gap-6">
        <Link
          href="/"
          className="flex rounded-lg bg-blue-500 p-2 text-white transition-colors hover:bg-blue-600"
        >
          Home
        </Link>
        <Link
          href="/react/richtext"
          className="flex rounded-lg bg-blue-500 p-2 text-white transition-colors hover:bg-blue-600"
        >
          Go to Rich Text Example
        </Link>
      </nav>
    </header>
  );
}

// packages/angular/playground/ssr/src/app/components/header/header.component.ts
import { Component } from '@angular/core';
import { RouterLink, RouterLinkActive } from '@angular/router';

@Component({
  selector: 'app-header',
  imports: [RouterLink, RouterLinkActive],
  template: `
    <header class="bg-slate-800 text-white px-8 py-4">
      <nav class="flex justify-between items-center max-w-7xl mx-auto">
        <a routerLink="/" class="text-2xl font-bold hover:opacity-80 transition-opacity">
          Storyblok Angular
        </a>
        <ul class="flex list-none gap-8 m-0 p-0">
          <li>
            <a
              routerLink="/"
              routerLinkActive="underline"
              [routerLinkActiveOptions]="{ exact: true }"
              class="text-white no-underline hover:opacity-80 transition-opacity"
            >
              Home
            </a>
          </li>
          <li>
            <a
              routerLink="/about"
              routerLinkActive="underline"
              class="text-white no-underline hover:opacity-80 transition-opacity"
            >
              About
            </a>
          </li>
        </ul>
      </nav>
    </header>
  `,
})
export class HeaderComponent {}
