// packages/react/src/v2/StoryblokRichText.tsx
import { createRichTextRenderer } from ".";
import type { ReactNode } from "react";
import type { StoryblokRichTextProps } from "../core/richtext";

export function StoryblokRichText({
  document,
  optimizeImage,
  components,
}: StoryblokRichTextProps): ReactNode {
  const render = createRichTextRenderer({
    optimizeImage,
    components,
  });
  const content = render(document);
  return content;
}

// packages/vue/src/components/StoryblokRichText.vue
<script lang="ts">
import { defineComponent } from 'vue';
import type { PropType } from 'vue';
import type { SbRichTextImageOptions, SbRichTextInput } from '@storyblok/richtext';
import BlokRenderer from './BlokRenderer.ts';
import { createRichTextRenderer, type SbVueRichTextComponentMap } from '../rich-text-renderer';

export default defineComponent({
  name: 'StoryblokRichText',
  props: {
    document: {
      type: Object as PropType<SbRichTextInput>,
      required: false,
    },
    optimizeImage: {
      type: [Boolean, Object] as PropType<boolean | SbRichTextImageOptions>,
      required: false,
    },
    components: {
      type: Object as PropType<SbVueRichTextComponentMap>,
      required: false,
    },
    data: {
      type: null as unknown as PropType<unknown>,
      required: false,
    },
  },

  setup(props) {
    const render = createRichTextRenderer({
      optimizeImage: props.optimizeImage,
      components: {
        blok: BlokRenderer,
        ...props.components,
      },
      data: props.data,
    });
    return () => render(props.document);
  },
});
</script>
