// packages/vue/playground/vue/src/components/Grid.vue
<script setup lang="ts">
import type { SbBlokData } from '@storyblok/vue';

defineProps<{ blok: SbBlokData & { columns?: SbBlokData[] } }>();
</script>

<template>
  <div v-editable="blok" class="flex py-8 mb-6" data-test="grid">
    <div v-for="inblok in blok.columns" :key="inblok._uid" class="flex-auto px-6">
      <StoryblokComponent :blok="inblok" />
    </div>
  </div>
</template>

// packages/react/playground/integration-tests/components/grid.tsx
import type { StoryblokComponentProps } from "@storyblok/react";
import { StoryblokComponent } from "../storyblok";
import { Block } from "../schema/blocks";

type GridProps = StoryblokComponentProps<Block<"grid">>;

const Grid = ({ block, editable }: GridProps) => {
  if (!block.columns) {
    return null;
  }

  return (
    <ul {...editable} data-test="grid">
      {block.columns.map((nestedBlock) => (
        <li key={nestedBlock._uid}>
          <StoryblokComponent block={nestedBlock} />
        </li>
      ))}
    </ul>
  );
};

export default Grid;
