// packages/vue/playground/vue/src/components/Feature.vue
<script setup lang="ts">
import type { SbBlokData } from "@storyblok/vue";

defineProps<{ blok: SbBlokData & { name?: string } }>();

function featureMethod() {
  // eslint-disable-next-line no-console
  console.log("Hi from Feature.vue");
}

defineExpose({
  featureMethod,
});
</script>

<template>
  <div v-editable="blok" class="py-2" data-test="feature">
    <h1 class="text-lg">{{ blok.name }}</h1>
  </div>
</template>

// packages/react/playground/next-13-app-router/components/Feature.tsx
import type { StoryblokBlockComponentProps } from "@storyblok/react";

type FeatureProps = StoryblokBlockComponentProps<{
  name: string;
  description: string;
}>;

const Feature = ({ block, editable }: FeatureProps) => (
  <div data-test="feature" {...editable}>
    <div>{block.name}</div>
    <p>{block.description}</p>
  </div>
);

export default Feature;
