// packages/vue/playground/vue/src/components/Grid.vue
<script setup lang="ts">
import type { SbBlokData } from '@storyblok/vue';

defineProps<{ blok: SbBlokData & { columns?: SbBlokData[] } }>();
</script>

<template>
  <div v-editable="blok" class="flex py-8 mb-6" data-test="grid">
    <div v-for="inblok in blok.columns" :key="inblok._uid" class="flex-auto px-6">
      <StoryblokComponent :blok="inblok" />
    </div>
  </div>
</template>

// packages/react/playground/next-13-app-router/components/Grid.tsx
import type { BlockContent, StoryblokComponentProps } from "@storyblok/react";
import { StoryblokComponent } from "@/lib/storyblok";

type GridProps = StoryblokComponentProps<{ columns: BlockContent[] }>;

const Grid = ({ block, editable }: GridProps) => {
  if (!block.columns) return null;

  return (
    <ul data-test="grid" {...editable}>
      {block.columns.map((column) => (
        <li key={column._uid}>
          <StoryblokComponent block={column} />
        </li>
      ))}
    </ul>
  );
};

export default Grid;
