// packages/react/playground/react/components/grid.tsx
import React from "react";
import type { SbBlokData } from "@storyblok/react";
import { StoryblokComponent, storyblokEditable } from "@storyblok/react";

interface GridProps {
  blok: SbBlokData;
}

const Grid = ({ blok }: GridProps) => (
  <ul {...storyblokEditable(blok)} key={blok._uid} data-test="grid">
    {(blok.columns as SbBlokData[]).map((nestedBlok) => (
      <li key={nestedBlok._uid}>
        <StoryblokComponent blok={nestedBlok} />
      </li>
    ))}
  </ul>
);

export default Grid;

// packages/nuxt/playground/app/storyblok/sub/Grid.vue
<script setup lang="ts">
defineProps({
  blok: {
    type: Object,
    required: true,
  },
});
</script>

<template>
  <div v-editable="blok" class="flex py-8 mb-6" data-test="grid">
    <div v-for="subBlok in blok.columns" :key="subBlok._uid" class="flex-auto px-6">
      <StoryblokComponent :blok="subBlok" />
    </div>
  </div>
</template>
