// packages/vue/playground/vue/src/components/Teaser.vue
<script setup lang="ts">
import type { SbBlokData } from '@storyblok/vue';

defineProps<{ blok: SbBlokData & { headline?: string } }>();
</script>

<template>
  <div
    v-editable="blok"
    :cat="$attrs.cat"
    class="py-8 mb-6 text-5xl font-bold text-center"
    data-test="teaser"
  >
    {{ blok.headline }}
  </div>
</template>

// packages/react/playground/next-latest/src/app/components/Teaser.tsx
import type { SbBlokData } from '@storyblok/react';
import { storyblokEditable } from '@storyblok/react/rsc';

interface TeaserBlok extends SbBlokData {
  headline: string;
}

const Teaser = ({ blok }: { blok: TeaserBlok }) => {
  return (
    <h2 data-cy="teaser" {...storyblokEditable(blok)}>
      {blok.headline}
    </h2>
  );
};

export default Teaser;
